version: '3.1'

services:
    app:
        build: .
        command: npm run build
        environment:
            NODE_ENV: production
        ports:
            - '3000:3000'
        volumes:
            - .:/home/app/javaskript/
            - /home/app/javaskript/node_modules
